### ISSUE TITLE
実際に使ってみて、速く、楽に、頭への負担が少なく打てるでしょうか？

### ISSUE THREAD

**Issue by oyayubikun** [semialt/komadori#28]
現在NICOLAで入力しています。
こまどり配列は、ポケベル打ちみたいだし、キーボードの制約がないのでいいですね。
今後、NICOLAをやろうという人がいてもこの配列のほうがいいかもしれません。
しかし、中段しか使わない点はいいのですが、２打が必要ということで、ローマ字入力よりもいいとしても、NICOLAよりも良くはないのかもしれません。
実際に使ってみて、速く、楽に、頭への負担が少なく打てるでしょうか？

**Comment by semialt** [comment]
こまどり配列は実用的な速度で使える配列で、私は新配列の実験をしているとき以外は職場でも自宅でも（今もこの文章を打っているときも）こまどり配列で入力しています。
　こまどり配列は中段の使用率が非常に高いため、ローマ字入力より楽に打てる配列と感じていますが、約半年使った現段階では、長年使ってきたローマ字入力（正確にはAZIK）よりは打鍵速度は遅いです。それでもこまどり配列の方が楽で疲れないこと、十分実用的な速度で使えていることから、こまどり配列を常用しています。
　頭への負担は特に感じません。多分、他の配列のタッチタイピングになれた場合と同じくらいかと。
　こまどり配列の打鍵数はローマ字入力より若干よいですが、あくまで行段系の配列であり、NOCOLAなどのかな配列ほどの打鍵効率はありません。
　例えば、こちらの例文（ https://esrille.github.io/keyboard-layout-comparison/ ）では打鍵数がそれぞれ

ローマ字入力　203
こまどり　188
Nicola (親指シフト)　170

となります。（シフトも１打鍵と数えた場合です）

打鍵効率や速度を求めるなら、NOCOLAなどのかな配列系が優れているのは間違いないです。こまどり配列はあくまで、「一段で打てる」のが楽でいいと感じる人のための配列です。
