### ISSUE TITLE
同時打鍵にするとどうでしょうか？

### ISSUE THREAD

**Issue by oyayubikun** [semialt/komadori#29]
一列しか使わないのは、ステノワードみたいで将来性がありそうですね。
五十音だけでもDvorakJなどを使って、同時打鍵にするとどうでしょうか？
あっ！そうなると逆順の組み合わせを排除して別で割り当てないとなりませんね。

**Comment by semialt** [comment]
逆順だけではなく、同手のパターンもほとんど外さないといけないので、ぜんぜん違う配列になります。

同時打鍵、行段の配列で私が作ったものとして、

かな入力が一段でできるが、濁音の入力にスペースキーによるシフトを使う「はちどり配列」（開発中止。設定ファイル公開予定なし）
https://github.com/semialt/hachidori

かな入力に上段も積極的に使う配列として、「よだか配列」（開発中）
https://github.com/semialt/yodaka

の２つがあります。

なお、シフトキーも使わず、６つのキーだけでかなが入力できる六点入力という配列もありますよ。
http://www.global0040.com/tenji_grap.html
